
# Audio processing parameters  
frame_length: 4096
hop_length: 1024
window: hamming
win_length: 4096

# Pattern processing
pattern_mode: bytes2bipolar  # bits2bipolar, bytes2bipolar

# Watermark parameters
embedding_bands: [1000, 3000]  # frequency range for embedding (Hz)
tolerance_db: 15.0  # lower = stronger watermark, higher = weaker watermark

# Optimization parameters
num_iterations: 2000
optimizer_cfg: 
  name: adam  # adam, nadam, sgd
  params:
    lr: 0.001
scheduler_cfg: 
  name: cosine  # reduce_lr_on_plateau, cosine, linear
  params:
    factor: 0.5
    patience: 100
loss: push_sigmoid  # hinge, mse, push_extremes, push_sigmoid, sign, bce, ber

# Logging
verbose: true

# Detection network configuration
detection_net_cfg:
  sample_rate: 48000  
  n_fft: 2048
  n_mels: 256
  num_blocks: 4
  initial_pool_size: 4
  initial_pool_stride: 4
  n_filters: [512, 1024, 2048, 4096]
  activation: relu
  watermark_length: 20
  final_activation: sigmoid

# Detection parameters
threshold: 0
